### ISSUE TITLE
pretrained model files

### ISSUE THREAD

**Issue by Ao-Lee** [HCIILAB/Scene-Text-Recognition-Recommendations#4]
I would like to ask is pretrained model files available to download?

**Comment by Mountchicken** [comment]
Hi @Ao-Lee 
Download links have been updated.

**Comment by Ao-Lee** [comment]
Thanks. I still cannot access the checkpoint for ASTER. I guess the accessing code is not 'dlvc'

**Comment by Mountchicken** [comment]
@Ao-Lee 
Just checked. `DLVC` should work.

**Comment by Ao-Lee** [comment]
it works, thank you
