### ISSUE TITLE
lib dependencies

### ISSUE THREAD

**Issue by Ao-Lee** [HCIILAB/Scene-Text-Recognition-Recommendations#5]
Hi, when I try to run inference.sh. I stuck with the following error:
```
File "HCIILAB\lib\evaluation_metrics\metrics.py", line 9, in <module>
    import editdistance
ModuleNotFoundError: No module named 'editdistance'
```
I guess I can simply remove the line "import editdistance"

and then after rerunning the scripts, I got the following error:

```
File "HCIILAB\lib\models\model_builder_CTC.py", line 3, in <module>
    import einops
ModuleNotFoundError: No module named 'einops'
```

I would like to ask which lib dependencies are necessary for this project except pytorch? Or would you please update an requirement.txt file? 

Thanks in advance

**Comment by Mountchicken** [comment]
Hi @Ao-Lee 
Done! Please update for the latest verision.

**Comment by Ao-Lee** [comment]
thank you!
