### ISSUE TITLE
Unable to download datasets

### ISSUE THREAD

**Issue by mariaalfaroc** [HCIILAB/Scene-Text-Recognition-Recommendations#6]
Hi!

I'm having trouble downloading the "Other real datasets". When I clicked on the link,  it said that "they are no longer available". Is there any other way to download them?

Thank you for your help :)
<img width="847" alt="Screenshot 2023-03-29 at 16 22 39" src="https://user-images.githubusercontent.com/56754030/228570788-a35fe587-aeef-43e1-a0c3-0cf18a08f6bc.png">

**Comment by Mountchicken** [comment]
Hi @mariaalfaroc 
It looks like the download link has expired. However, you can also download those real datasets from [https://github.com/ku21fan/STR-Fewer-Labels/issues/4#issuecomment-950785928](https://github.com/ku21fan/STR-Fewer-Labels/issues/4#issuecomment-950785928)
