### ISSUE TITLE
add ICCV 2023 paper 

### ISSUE THREAD

**Issue by simplify23** [HCIILAB/Scene-Text-Recognition-Recommendations#7]
Paper name/title: MRN: Multiplexed Routing Network for Incremental Multilingual Text Recognition
Paper link: https://arxiv.org/abs/2305.14758
Code link: https://github.com/simplify23/MRN
Blog in Chinese: https://zhuanlan.zhihu.com/p/643948935
keywords: OCR, Incremental learning

**Comment by Mountchicken** [comment]
Done!

**Comment by TongkunGuan** [comment]
Hello! Could you add our work?
Paper name/title: Self-supervised Character-to-Character Distillation for Text Recognition
Paper link: https://openaccess.thecvf.com/content/ICCV2023/papers/Guan_Self-Supervised_Character-to-Character_Distillation_for_Text_Recognition_ICCV_2023_paper.pdf
Code link: https://github.com/TongkunGuan/CCD
Keywords: OCR, SSL
