### ISSUE TITLE
Add ICCV2023 paper

### ISSUE THREAD

**Issue by TongkunGuan** [HCIILAB/Scene-Text-Recognition-Recommendations#9]
Hello! Could you add our work?
Paper name/title: Self-supervised Character-to-Character Distillation for Text Recognition
Paper link: https://openaccess.thecvf.com/content/ICCV2023/papers/Guan_Self-Supervised_Character-to-Character_Distillation_for_Text_Recognition_ICCV_2023_paper.pdf
Code link: https://github.com/TongkunGuan/CCD
Keywords: OCR, SSL

**Comment by Mountchicken** [comment]
Sure

**Comment by TongkunGuan** [comment]
> Sure

Thanks!
